// App-facing types.
//
// The capture/screen/flow model IS the packager's derived View — re-exported here
// under the app's vocabulary so there is a single source of truth (no duplicate or
// legacy schema). Only the registry/manifest/search types, which describe the
// static-build data layout rather than the capture itself, are defined here.

export type {
  Platform,
  ScreenRole,
  StateLabel,
  InteractiveElement,
  ReplayCommand,
} from "./packager/types"

import type {
  Platform,
  View,
  ViewScreen,
  ViewFlow,
  ViewStep,
  ViewReplay,
} from "./packager/types"

// The app vocabulary, aliased over the derived View.
export type AppCapture = View
export type ScreenEntry = ViewScreen
export type FlowEntry = ViewFlow
export type FlowStep = ViewStep
export type FlowReplay = ViewReplay

export interface DecisionPointOption {
  label: string
  explored: boolean
  flowSlug?: string
}
export interface DecisionPoint {
  screenId: string
  options: DecisionPointOption[]
}

export interface AppMeta {
  name: string
  slug: string
  bundleId: string
  platform: Platform
}

// Per-app manifest (app.json): capture history index.
export interface CaptureIndexEntry {
  date: string
  scope: string
  mode: string
  previousCapture: string | null
  path: string
}
export interface AppManifest {
  schemaVersion: number
  app: AppMeta
  firstCapturedAt: string
  lastCapturedAt: string
  latestCapture: string
  captures: CaptureIndexEntry[]
}

// Global registry (index.json — generated by the data build).
export interface AppIndex {
  slug: string
  name: string
  platform: Platform
  captures: string[]
  latest: string
}
export interface AppsRegistry {
  apps: AppIndex[]
}

// Search index (search-index.json — generated by the data build).
export interface SearchEntry {
  type: "app" | "screen" | "flow" | "step"
  appSlug: string
  appName: string
  label: string
  description?: string
  href: string
  screenId?: string
  flowSlug?: string
  flowName?: string
}
